Added publish on tag to CI.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -224,6 +224,39 @@ test-notebooks:
         --progress-bar -k python3 --stdout-file - --stderr-file -
         "${NOTEBOOK_FILE}" /dev/null
 
+# When a tag is created matching the release pattern, build and publish our
+# package to PYPI.
+publish-on-tag:
+  extends:
+    - .run_on_upstream_version_tag
+    - .setup_poetry
+  # Note: using of default image/interruptable/tags
+  stage: publish
+  script:
+    # Ensure there is alignment with the tag reference and the reported
+    # version of the package
+    - |
+      PACKAGE_VERSION="v$(poetry version -s)"
+      if [[ "${CI_COMMIT_TAG}" != "${PACKAGE_VERSION}" ]]
+      then
+        echo "ERROR: Git tag reference and package version are NOT synonymous."
+        echo "       Package version: ${PACKAGE_VERSION}"
+        echo "       Git ref name   : ${CI_COMMIT_TAG}"
+        exit 1
+      fi
+    # Ensure that we have token
+    - |
+      if [[ -z "${PYPI_PUBLISH_TOKEN}" ]]
+      then
+        echo "ERROR: Expected PYPI token variable was blank."
+        echo "       Did you forget to set the appropriate PYPI_PUBLISH_TOKEN secret?"
+        exit 1
+      fi
+    # Actually publish
+    - |
+      export POETRY_PYPI_TOKEN_PYPI="${PYPI_PUBLISH_TOKEN}"
+      poetry publish --build
+
 pages:
   stage: docs
   needs:
